apiVersion: v1
kind: Service
metadata:
  name: ecommerce-mock-service
spec:
  selector:
    app: ecommerce-mock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
