name: Build E-Commerce Application

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python environment
      run: |
        DEBUG "Setting up Python virtual environment..."
        python3 -m venv venv-env  # Create the virtual environment
        source venv-env/bin/activate
        pip install --upgrade pip
        pip install --no-deps --upgrade -r requirements.txt

    - name: Run tests
      run: |
        DEBUG "Running tests..."
        source venv-env/bin/activate
        pytest --maxfail=5 --disable-warnings --verbose
        DEBUG "Tests completed."

  build:
    runs-on: self-hosted
    needs: test

    steps:
    - name: Check out code
      uses: actions/checkout@v3  

    - name: Set up Python environment
      run: |
        DEBUG "Setting up Python virtual environment..."
        python3 -m venv venv-env  # Create the virtual environment
        source venv-env/bin/activate
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install --no-deps --upgrade -r requirements.txt

    - name: Build Docker image
      run: |
        DEBUG "Building Docker image..."
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-mock:latest .
        DEBUG "Docker image built."

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        DEBUG "Pushing Docker image to Docker Hub..."
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-mock:latest
        DEBUG "Docker image pushed to Docker Hub."
