name: Build and Deploy E-Commerce Application

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python3 -m venv venv-env
        source venv-env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv-env/bin/activate
        pytest --maxfail=5 --disable-warnings

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-mock:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-mock:latest

    - name: Deploy with Helm
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        helm upgrade --install e-commerce-mock ./e-commerce-mock \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/ecommerce-mock \
          --set image.tag=latest
